// <auto-generated />
namespace Iss.LiveClassRoom.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ignorechanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ignorechanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201606090836556_ignore changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
