//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="EnrollStudentService")]
public interface EnrollStudentService
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/EnrollStudentService/RecvEnrollmentReq")]
    void RecvEnrollmentReq(string studentId, string courseId);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/EnrollStudentService/RecvEnrollmentReq")]
    System.Threading.Tasks.Task RecvEnrollmentReqAsync(string studentId, string courseId);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/EnrollStudentService/EnrollDecision")]
    void EnrollDecision(bool isAccept, string studentId, string courseId);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/EnrollStudentService/EnrollDecision")]
    System.Threading.Tasks.Task EnrollDecisionAsync(bool isAccept, string studentId, string courseId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface EnrollStudentServiceChannel : EnrollStudentService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EnrollStudentServiceClient : System.ServiceModel.ClientBase<EnrollStudentService>, EnrollStudentService
{
    
    public EnrollStudentServiceClient()
    {
    }
    
    public EnrollStudentServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EnrollStudentServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EnrollStudentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EnrollStudentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void RecvEnrollmentReq(string studentId, string courseId)
    {
        base.Channel.RecvEnrollmentReq(studentId, courseId);
    }
    
    public System.Threading.Tasks.Task RecvEnrollmentReqAsync(string studentId, string courseId)
    {
        return base.Channel.RecvEnrollmentReqAsync(studentId, courseId);
    }
    
    public void EnrollDecision(bool isAccept, string studentId, string courseId)
    {
        base.Channel.EnrollDecision(isAccept, studentId, courseId);
    }
    
    public System.Threading.Tasks.Task EnrollDecisionAsync(bool isAccept, string studentId, string courseId)
    {
        return base.Channel.EnrollDecisionAsync(isAccept, studentId, courseId);
    }
}
